ALTER TABLE APP.BANK
ADD FOREIGN KEY (BANK_ACCOUNT_ID) 
REFERENCES APP.PEOPLE(BANK_ACCOUNT_ID);

ALTER TABLE APP.BANK
ADD FOREIGN KEY (TASK_ID) 
REFERENCES APP.TASK(TASK_ID);

ALTER TABLE APP.REPUTATION
ADD FOREIGN KEY (PERSON_ID) 
REFERENCES APP.PEOPLE(PERSON_ID)
ON DELETE CASCADE;

CREATE SEQUENCE APP.bank_id
AS BIGINT
START WITH 0;

CREATE SEQUENCE APP.people_id
AS BIGINT
START WITH 0;

CREATE SEQUENCE APP.reputation_id
AS BIGINT
START WITH 0;

CREATE SEQUENCE APP.task_id
AS BIGINT
START WITH 0;

CREATE SEQUENCE APP.SEQUENCE
AS BIGINT
START WITH 0;

DROP SEQUENCE APP.SEQUENCE RESTRICT;

DROP TABLE APP.SEQUENCE;
CREATE TABLE APP.SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME));

INSERT INTO APP.SEQUENCE (SEQ_NAME, SEQ_COUNT) VALUES ("TASK_SEQ_GEN",0);

select NEXT VALUE FOR APP.task_id;

SELECT NEXT VALUE FOR APP.task_id
  FROM APP.PEOPLE;

select nextval from APP.task_id;


ALTER TABLE APP.TASK ADD TASK_NAME VARCHAR(255);
--CREATE SEQUENCE DBSRTY0.FAQRF011_SEQ AS DECIMAL(15,0)
-- INCREMENT BY 1
-- START WITH 1
-- NOMAXVALUE
-- MINVALUE 1
-- NOCYCLE
-- CACHE 02
-- NOORDER