DROP TABLE APP.BANK;

CREATE TABLE APP.BANK
    (BANK_ACCOUNT_ID INT NOT NULL, TRANSACTION_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, TRANSACTION_DATE DATE NOT NULL,
    TRANSACTION_TYPE VARCHAR(1), AMOUNT INT DEFAULT 0, TASK_ID INT NOT NULL, PRIMARY KEY (TRANSACTION_ID));

DROP TABLE APP.PEOPLE;
    
CREATE TABLE APP.PEOPLE
    (PERSON_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, BANK_ACCOUNT_ID INT NOT NULL,
    PERSON_LNAME VARCHAR(15), PERSON_FNAME VARCHAR(15), PERSON_ADDRESS VARCHAR(30),
    PRIMARY KEY (PERSON_ID), UNIQUE (BANK_ACCOUNT_ID));
    
DROP TABLE APP.REPUTATION;
    
CREATE TABLE APP.REPUTATION
    (REPUTATION_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, PERSON_ID INT NOT NULL,
    REPUTATION_SCORE INT NOT NULL DEFAULT 0,
    PRIMARY KEY (REPUTATION_ID));
    
DROP TABLE APP.TASK;
    
CREATE TABLE APP.TASK
    (TASK_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, CLIENT_PERSON_ID INT NOT NULL, PROVIDER_PERSON_ID INT,
    TASK_STATUS VARCHAR(1) NOT NULL DEFAULT 'P', TASK_TYPE VARCHAR(1), PARENT_TASK_ID INT,
    PRIMARY KEY (TASK_ID));