CREATE TABLE REPUTATION (
		REPUTATION_ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 4),
		PERSON_ID INTEGER NOT NULL,
		REPUTATION_SCORE INTEGER DEFAULT 0 NOT NULL
	);

CREATE TABLE BANK (
		BANK_ACCOUNT_ID INTEGER NOT NULL,
		TRANSACTION_ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 2),
		TRANSACTION_DATE DATE NOT NULL,
		TRANSACTION_TYPE VARCHAR(1),
		AMOUNT INTEGER DEFAULT 0,
		TASK_ID INTEGER NOT NULL
	);

CREATE TABLE PEOPLE (
		PERSON_ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 3),
		BANK_ACCOUNT_ID INTEGER NOT NULL,
		PERSON_LNAME VARCHAR(15),
		PERSON_FNAME VARCHAR(15),
		PERSON_ADDRESS VARCHAR(30)
	);

CREATE TABLE TASK (
		TASK_ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 2),
		CLIENT_PERSON_ID INTEGER NOT NULL,
		PROVIDER_PERSON_ID INTEGER,
		TASK_STATUS VARCHAR(1) DEFAULT 'P' NOT NULL,
		TASK_TYPE VARCHAR(1),
		PARENT_TASK_ID INTEGER
	);

CREATE UNIQUE INDEX SQL110802164800951 ON PEOPLE (null);

CREATE INDEX SQL110805172515680 ON REPUTATION (null);

CREATE UNIQUE INDEX SQL110802170552530 ON REPUTATION (null);

CREATE UNIQUE INDEX SQL110802170550090 ON BANK (null);

CREATE UNIQUE INDEX SQL110802170554810 ON TASK (null);

CREATE UNIQUE INDEX SQL110802164800950 ON PEOPLE (null);

ALTER TABLE REPUTATION ADD CONSTRAINT SQL110802170552530 PRIMARY KEY (REPUTATION_ID);

ALTER TABLE BANK ADD CONSTRAINT SQL110802170550090 PRIMARY KEY (TRANSACTION_ID);

ALTER TABLE PEOPLE ADD CONSTRAINT SQL110802164800950 PRIMARY KEY (PERSON_ID);

ALTER TABLE TASK ADD CONSTRAINT SQL110802170554810 PRIMARY KEY (TASK_ID);

ALTER TABLE REPUTATION ADD CONSTRAINT SQL110805172515680 FOREIGN KEY (PERSON_ID)
	REFERENCES PEOPLE (PERSON_ID);

