ALTER TABLE APP.BANK
ADD FOREIGN KEY (BANK_ACCOUNT_ID) 
REFERENCES APP.PEOPLE(BANK_ACCOUNT_ID);

ALTER TABLE APP.BANK
ADD FOREIGN KEY (TASK_ID) 
REFERENCES APP.TASK(TASK_ID);

ALTER TABLE APP.REPUTATION
ADD FOREIGN KEY (PERSON_ID) 
REFERENCES APP.PEOPLE(PERSON_ID)
ON DELETE CASCADE;

CREATE SEQUENCE APP.bank_id
AS BIGINT
START WITH 0;

CREATE SEQUENCE APP.people_id
AS BIGINT
START WITH 0;

CREATE SEQUENCE APP.reputation_id
AS BIGINT
START WITH 0;

CREATE SEQUENCE APP.task_id
AS BIGINT
START WITH 0;

CREATE SEQUENCE APP.SEQUENCE
AS BIGINT
START WITH 0;

DROP SEQUENCE APP.SEQUENCE RESTRICT;

DROP TABLE APP.SEQUENCE;
CREATE TABLE APP.SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME));

INSERT INTO APP.SEQUENCE (SEQ_NAME, SEQ_COUNT) VALUES ("TASK_SEQ_GEN",0);

select NEXT VALUE FOR APP.task_id;

SELECT NEXT VALUE FOR APP.task_id
  FROM APP.PEOPLE;

select nextval from APP.task_id;

ALTER TABLE APP.TASK DROP COLUMN CLIENT_PAY; INT;

ALTER TABLE APP.TASK ADD TASK_NAME VARCHAR(255);

ALTER TABLE APP.TASK ADD TASK_DESC VARCHAR(255);
ALTER TABLE APP.TASK ADD CLIENT_PAY INT;
ALTER TABLE APP.TASK ADD TASK_DURATION INT;
ALTER TABLE APP.TASK ADD SENSED_DATA_FILE_LOCATION VARCHAR(255);

ALTER TABLE APP.TASK ADD Accelerometer VARCHAR(255);
ALTER TABLE APP.TASK ADD GPS VARCHAR(255);
ALTER TABLE APP.TASK ADD Camera VARCHAR(255);
ALTER TABLE APP.TASK ADD Mic VARCHAR(255);
ALTER TABLE APP.TASK ADD WiFi VARCHAR(255);
ALTER TABLE APP.TASK ADD Bluetooth VARCHAR(255);
ALTER TABLE APP.TASK ADD Magnetometer VARCHAR(255);
ALTER TABLE APP.TASK ADD ProximitySensor VARCHAR(255);
ALTER TABLE APP.TASK ADD AmbientLightSensor VARCHAR(255);

ALTER TABLE APP.PEOPLE ADD EMAILID VARCHAR(255);
ALTER TABLE APP.PEOPLE ADD PASSWORD VARCHAR(255);
ALTER TABLE APP.PEOPLE ADD GENDER VARCHAR(255);
ALTER TABLE APP.PEOPLE ADD NJIT_DEPARTMENT VARCHAR(255);
ALTER TABLE APP.PEOPLE ADD NJIT_ACADEMIC_YEAR VARCHAR(255);
ALTER TABLE APP.PEOPLE ADD AGE_GROUP VARCHAR(255);
ALTER TABLE APP.PEOPLE ADD MEID VARCHAR(255);

ALTER TABLE APP.TASK ADD TASK_ACCEPTED_TIME TIMESTAMP;
ALTER TABLE APP.TASK ADD TASK_COMPLETION_TIME TIMESTAMP;
ALTER TABLE APP.TASK ADD TASK_EXPIRATION_TIME TIMESTAMP;
ALTER TABLE APP.TASK ADD TASK_CREATED_TIME TIMESTAMP;

--CREATE SEQUENCE DBSRTY0.FAQRF011_SEQ AS DECIMAL(15,0)
-- INCREMENT BY 1
-- START WITH 1
-- NOMAXVALUE
-- MINVALUE 1
-- NOCYCLE
-- CACHE 02
-- NOORDER