ALTER TABLE APP.BANK
ADD FOREIGN KEY (BANK_ACCOUNT_ID) 
REFERENCES APP.PEOPLE(BANK_ACCOUNT_ID);

ALTER TABLE APP.BANK
ADD FOREIGN KEY (TASK_ID) 
REFERENCES APP.TASK(TASK_ID);

ALTER TABLE APP.REPUTATION
ADD FOREIGN KEY (PERSON_ID) 
REFERENCES APP.PEOPLE(PERSON_ID);